### ISSUE TITLE
Intermittent error that requires us to restart Geoserver

### ISSUE THREAD

**Issue by albertwgchu** [ngageoint/elasticgeo#122]
We are getting this Intermittent error with Geoserver 2.16.0.  Just wondering if anyone has some insight into this.

ERROR [data.elasticsearch] - Request cannot be executed; I/O reactor status: STOPPED
java.lang.RuntimeException: Request cannot be executed; I/O reactor status: STOPPED
at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:796)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:205)
at mil.nga.giat.data.elasticsearch.RestElasticClient.performRequest(RestElasticClient.java:263)
at mil.nga.giat.data.elasticsearch.RestElasticClient.performRequest(RestElasticClient.java:271)
at mil.nga.giat.data.elasticsearch.RestElasticClient.search(RestElasticClient.java:224)
at mil.nga.giat.data.elasticsearch.ElasticFeatureSource.getCountInternal(ElasticFeatureSource.java:94)
at org.geotools.data.store.ContentFeatureSource.getCount(ContentFeatureSource.java:463)
at org.geotools.data.store.ContentFeatureCollection.size(ContentFeatureCollection.java:225)
at org.geotools.feature.collection.DecoratingSimpleFeatureCollection.size(DecoratingSimpleFeatureCollection.java:108)
at org.geotools.data.crs.ReprojectFeatureResults.size(ReprojectFeatureResults.java:117)
at org.geotools.feature.collection.DecoratingFeatureCollection.size(DecoratingFeatureCollection.java:88)
at org.geoserver.wfs.GetFeature.run(GetFeature.java:649)
at org.geoserver.wfs.DefaultWebFeatureService.getFeature(DefaultWebFeatureService.java:105)
at jdk.internal.reflect.GeneratedMethodAccessor408.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)

**Comment by albertwgchu** [comment]
In case this helps anyone, we had a single store with multiple layers which were reading from different geometry fields.  Adding a separate store for each geometry avoided this issue.
