### ISSUE TITLE
Deploying precompiled binaries, Geoserver does not start properly

### ISSUE THREAD

**Issue by seainside75** [ngageoint/elasticgeo#14]
Hi,

I tried to deploy the precompiled binaries on both Geoserver 2.8.1 version and Geoserver 2.7.4 version on a Windows 7 machine with java 1.8.x without success.
What I get is

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
2016-05-11 23:26:00.377::INFO:  Logging to STDERR via org.mortbay.log.StdErrLog
2016-05-11 23:26:00.511::WARN:  Deprecated configuration used for C:\GeoServer 2.8.3/webapps
2016-05-11 23:26:00.549::INFO:  jetty-6.1.8
0    [main] WARN  org.geotools.factory  - Can't load a service for category "FilterFactory". Cause is "ServiceConfigurationError: org.opengis.filter.FilterFactory: Provider org.geotools.filter.FilterFactoryImpl could not be instantiated".
10   [main] WARN  org.geotools.factory  - Can't load a service for category "FilterFactory". Cause is "ServiceConfigurationError: org.opengis.filter.FilterFactory: Provider org.geotools.filter.FilterFactoryImpl could not be instantiated".
17   [main] WARN  org.geotools.factory  - Can't load a service for category "FilterFactory". Cause is "ServiceConfigurationError: org.opengis.filter.FilterFactory: Provider org.geotools.filter.FilterFactoryImpl could not be instantiated".
26   [main] WARN  org.geotools.factory  - Can't load a service for category "FilterFactory". Cause is "ServiceConfigurationError: org.opengis.filter.FilterFactory: Provider org.geotools.filter.FilterFactoryImpl could not be instantiated".
2016-05-11 23:26:03.173::WARN:  Failed startup of context org.mortbay.jetty.webapp.WebAppContext@1b266842{/geoserver,file:/C:/GeoServer%202.8.3/webapps/geoserver/}
org.geotools.factory.FactoryNotFoundException: No factory of kind "FilterFactory2" found.
        at org.geotools.factory.FactoryRegistry.getServiceProvider(FactoryRegistry.java:375)
        at org.geotools.factory.FactoryCreator.getServiceProvider(FactoryCreator.java:145)
        at org.geotools.factory.CommonFactoryFinder.lookup(CommonFactoryFinder.java:346)
        at org.geotools.factory.CommonFactoryFinder.getFilterFactory(CommonFactoryFinder.java:300)
        at org.geotools.factory.CommonFactoryFinder.getFilterFactory2(CommonFactoryFinder.java:390)
        at org.geoserver.GeoserverInitStartupListener.contextInitialized(GeoserverInitStartupListener.java:185)
        at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:540)
        at org.mortbay.jetty.servlet.Context.startContext(Context.java:135)
        at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1220)
        at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:510)
        at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
        at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
        at org.mortbay.jetty.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:156)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
        at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
        at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
        at org.mortbay.jetty.Server.doStart(Server.java:222)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
        at org.mortbay.xml.XmlConfiguration.main(XmlConfiguration.java:977)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mortbay.start.Main.invokeMain(Main.java:183)
        at org.mortbay.start.Main.start(Main.java:497)
        at org.mortbay.start.Main.main(Main.java:115)
2016-05-11 23:26:03.293::INFO:  Opened C:\GeoServer 2.8.3\logs\2016_05_11.request.log
2016-05-11 23:26:03.319::INFO:  Started SelectChannelConnector@0.0.0.0:8080

By using a Linux Centos 6.6 with open JDK 1,8 and Geoserver 2.7.x, it works

Are there some prerequisite for Windows 7 that I'm missing?

Thanks in advance

**Comment by sjudeng** [comment]
Is GeoServer installed through Tomcat or the windows installer? The windows installer docs for 2.7.x/2.8.x suggest Java 7 may be required. Does GeoServer start up okay if you remove the elasticgeo jar?

http://docs.geoserver.org/2.8.x/en/user/installation/win_installer.html

**Comment by seainside75** [comment]
Thanks for your reply. I deployed the elasticgeo succesfully...
