### ISSUE TITLE
Null pointer exception when creating multiple layers attached to same elastic search type with different geometry objects

### ISSUE THREAD

**Issue by jdobbs55** [ngageoint/elasticgeo#9]
Here are curl commands that will create an index in a local elastic search install to help reproduce this bug.

curl -XPUT 'http://localhost:9200/elasticgeo_index/'

curl -XPUT 'http://localhost:9200/elasticgeo_index/_mapping/bug' -d '
{
    "bug" : {
        "properties" : {
            "field1" : {"type" : "geo_shape", 
						"tree" : "quadtree",
						"tree_levels" : 18},
			"field2" : {"type" : "geo_shape",
						"tree" : "quadtree",
						"tree_levels" : 18}
        }
    }
}'

**Steps to reproduce:**
1. Add a new workspace called "workspace" to geoserver
2. Add an elastic search data source for index elasticgeo_index
3. Publish the layer named bug
4. Map field1 in the layer and save
5. Go to the add layer window and publish the bug layer again.  Close the popup window that appears
6. Name the layer bug2 and save
7. Map field2 this time and save
8. On the publishing tab for bug2 change "Default Style" to polygon
9. Run the following query that attempts to display both the bug and bug2 layers:  ```http://localhost/geoserver/workspace/wms?service=WMS&version=1.1.0&request=GetMap&layers=workspace:bug,workspace:bug2&styles=&bbox=-130.85168,20.7052,-62.0054,54.1141&width=768&height=372&srs=EPSG:4326&format=application/openlayers&viewparams=f:{"bool":{"must":{"geo_shape":{"bug.field1":{"shape":{"type":"envelope"\,"coordinates":[[-180\,90]\,[180\,-90]]}\,"relation":"within"}\,"_name":null}}}}```

**The following call stack will appear in geoserver's log:**

2015-10-08 18:19:26,077 INFO [geoserver.wms] - 
Request: getServiceInfo
2015-10-08 18:19:26,096 ERROR [geotools.rendering] - 
java.lang.NullPointerException
               at mil.nga.giat.data.elasticsearch.FilterToElasticHelper.visitBinarySpatialOperator(FilterToElasticHelper.java:174)
               at mil.nga.giat.data.elasticsearch.FilterToElasticHelper.visitComparisonSpatialOperator(FilterToElasticHelper.java:164)
               at mil.nga.giat.data.elasticsearch.FilterToElasticHelper.visitBinarySpatialOperator(FilterToElasticHelper.java:92)
               at mil.nga.giat.data.elasticsearch.FilterToElastic.visitBinarySpatialOperator(FilterToElastic.java:1176)
               at mil.nga.giat.data.elasticsearch.FilterToElastic.visitBinarySpatialOperator(FilterToElastic.java:708)
               at mil.nga.giat.data.elasticsearch.FilterToElastic.visit(FilterToElastic.java:650)
               at org.geotools.renderer.lite.FastBBOX.accept(FastBBOX.java:124)
               at mil.nga.giat.data.elasticsearch.FilterToElastic.encode(FilterToElastic.java:177)
               at mil.nga.giat.data.elasticsearch.FilterToElastic.encode(FilterToElastic.java:190)
               at mil.nga.giat.data.elasticsearch.ElasticFeatureSource.prepareSearchRequest(ElasticFeatureSource.java:180)
               at mil.nga.giat.data.elasticsearch.ElasticFeatureSource.getReaderInternal(ElasticFeatureSource.java:130)
               at org.geotools.data.store.ContentFeatureSource.getReader(ContentFeatureSource.java:612)
               at org.geotools.data.store.ContentFeatureCollection.features(ContentFeatureCollection.java:164)
               at org.geoserver.feature.RetypingFeatureCollection.features(RetypingFeatureCollection.java:46)
               at org.geoserver.feature.RetypingFeatureCollection.features(RetypingFeatureCollection.java:32)
               at org.geotools.renderer.lite.StreamingRenderer.drawPlain(StreamingRenderer.java:2388)
               at org.geotools.renderer.lite.StreamingRenderer.processStylers(StreamingRenderer.java:2113)
               at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:832)
               at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:539)
               at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:260)
               at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:132)
               at org.geoserver.wms.GetMap.executeInternal(GetMap.java:504)
               at org.geoserver.wms.GetMap.run(GetMap.java:248)
               at org.geoserver.wms.GetMap.run(GetMap.java:119)
               at org.geoserver.wms.DefaultWebMapService.getMap(DefaultWebMapService.java:369)
               at sun.reflect.GeneratedMethodAccessor258.invoke(Unknown Source)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.lang.reflect.Method.invoke(Method.java:606)
               at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
               at org.geoserver.kml.WebMapServiceKmlInterceptor.invoke(WebMapServiceKmlInterceptor.java:34)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
               at org.geoserver.gwc.wms.CacheSeedingWebMapService.invoke(CacheSeedingWebMapService.java:62)
               at org.geoserver.gwc.wms.CacheSeedingWebMapService.invoke(CacheSeedingWebMapService.java:36)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
               at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:74)
               at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:55)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
               at org.geoserver.ows.util.RequestObjectLogger.invoke(RequestObjectLogger.java:55)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
               at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
               at com.sun.proxy.$Proxy79.getMap(Unknown Source)
               at sun.reflect.GeneratedMethodAccessor221.invoke(Unknown Source)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.lang.reflect.Method.invoke(Method.java:606)
               at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:841)
               at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:275)
               at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
               at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
               at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
               at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
               at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
               at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
               at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
               at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75)
               at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71)
               at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
               at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
               at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
               at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
               at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
               at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
               at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
               at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:54)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
               at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
               at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
               at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:83)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
               at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
               at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
               at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
               at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
               at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:135)
               at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
               at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:83)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.vfny.geoserver.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)
               at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
               at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
               at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
               at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
               at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:559)
               at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
               at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
               at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
               at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
               at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)
               at java.lang.Thread.run(Thread.java:744)
2015-10-08 18:19:26,108 ERROR [geoserver.ows] - 
org.geoserver.platform.ServiceException: Rendering process failed
               at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:569)
               at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:260)
               at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:132)
               at org.geoserver.wms.GetMap.executeInternal(GetMap.java:504)
               at org.geoserver.wms.GetMap.run(GetMap.java:248)
               at org.geoserver.wms.GetMap.run(GetMap.java:119)
               at org.geoserver.wms.DefaultWebMapService.getMap(DefaultWebMapService.java:369)
               at sun.reflect.GeneratedMethodAccessor258.invoke(Unknown Source)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.lang.reflect.Method.invoke(Method.java:606)
               at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
               at org.geoserver.kml.WebMapServiceKmlInterceptor.invoke(WebMapServiceKmlInterceptor.java:34)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
               at org.geoserver.gwc.wms.CacheSeedingWebMapService.invoke(CacheSeedingWebMapService.java:62)
               at org.geoserver.gwc.wms.CacheSeedingWebMapService.invoke(CacheSeedingWebMapService.java:36)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
               at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:74)
               at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:55)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
               at org.geoserver.ows.util.RequestObjectLogger.invoke(RequestObjectLogger.java:55)
               at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
               at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
               at com.sun.proxy.$Proxy79.getMap(Unknown Source)
               at sun.reflect.GeneratedMethodAccessor221.invoke(Unknown Source)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.lang.reflect.Method.invoke(Method.java:606)
               at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:841)
               at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:275)
               at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
               at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
               at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
               at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
               at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
               at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
               at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
               at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75)
               at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71)
               at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
               at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
               at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
               at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
               at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
               at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
               at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
               at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:54)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
               at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
               at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
               at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:83)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
               at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
               at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53)
               at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
               at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
               at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
               at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
               at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:135)
               at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
               at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:83)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.vfny.geoserver.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
               at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
               at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
               at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)
               at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
               at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
               at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145)
               at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
               at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:559)
               at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
               at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
               at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856)
               at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
               at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)
               at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
               at mil.nga.giat.data.elasticsearch.FilterToElasticHelper.visitBinarySpatialOperator(FilterToElasticHelper.java:174)
               at mil.nga.giat.data.elasticsearch.FilterToElasticHelper.visitComparisonSpatialOperator(FilterToElasticHelper.java:164)
               at mil.nga.giat.data.elasticsearch.FilterToElasticHelper.visitBinarySpatialOperator(FilterToElasticHelper.java:92)
               at mil.nga.giat.data.elasticsearch.FilterToElastic.visitBinarySpatialOperator(FilterToElastic.java:1176)
               at mil.nga.giat.data.elasticsearch.FilterToElastic.visitBinarySpatialOperator(FilterToElastic.java:708)
               at mil.nga.giat.data.elasticsearch.FilterToElastic.visit(FilterToElastic.java:650)
               at org.geotools.renderer.lite.FastBBOX.accept(FastBBOX.java:124)
               at mil.nga.giat.data.elasticsearch.FilterToElastic.encode(FilterToElastic.java:177)
               at mil.nga.giat.data.elasticsearch.FilterToElastic.encode(FilterToElastic.java:190)
               at mil.nga.giat.data.elasticsearch.ElasticFeatureSource.prepareSearchRequest(ElasticFeatureSource.java:180)
               at mil.nga.giat.data.elasticsearch.ElasticFeatureSource.getReaderInternal(ElasticFeatureSource.java:130)
               at org.geotools.data.store.ContentFeatureSource.getReader(ContentFeatureSource.java:612)
               at org.geotools.data.store.ContentFeatureCollection.features(ContentFeatureCollection.java:164)
               at org.geoserver.feature.RetypingFeatureCollection.features(RetypingFeatureCollection.java:46)
               at org.geoserver.feature.RetypingFeatureCollection.features(RetypingFeatureCollection.java:32)
               at org.geotools.renderer.lite.StreamingRenderer.drawPlain(StreamingRenderer.java:2388)
               at org.geotools.renderer.lite.StreamingRenderer.processStylers(StreamingRenderer.java:2113)
               at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:832)
               at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:539)
               ... 110 more

**Comment by sjudeng** [comment]
Thanks for the bug report and steps to reproduce the issue. I'll look at adding support for multiple layers from the same Elasticsearch mapping type. I have an idea what needs to be changed, but it's not a quick fix.

In the meantime, it might be possible to create a single layer with the multiple geometry columns and then vary the geometry column through the filter/SLD in your WFS/WMS requests.

**Comment by sjudeng** [comment]
I just pushed a change that hopefully resolves this issue. Unfortunately I think you'll need to delete and reload relevant layers in GeoServer after you've updated. It shouldn't be necessary to delete old Elasticsearch stores, just the layers.

**Comment by jdobbs55** [comment]
Thanks for fixing the issue.  My team wants to wait to try the new version because the workaround we’re using seems to work for our use cases.
